version: "3"
services:
  db:
    restart: always
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    container_name: "my_mysql8"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=jdev
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
# docker inspect  {postgressContainerID} | grep IPAddress
